# Generated by Django 3.0.5 on 2020-05-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200523_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
